---
#- name: add new apt repo
#  apt_repository: repo='ppa:webupd8team/java'

- name: jdk
  apt: pkg=default-jdk state=present
  become: root 

- name: Update apt cache
  apt: update_cache=yes

- file: path=/opt/tomcat state=directory mode=0777

- name: get tomcat
  get_url: url=http://mirror.sdunix.com/apache/tomcat/tomcat-8/v8.0.32/bin/apache-tomcat-8.0.32-deployer.tar.gz dest=/opt/tomcat/tomcat.tar.gz

- unarchive: src=/opt/tomcat/tomcat.tar.gz dest=/opt/tomcat/
