---
- name: Retrieve stuff from mysql
  command: >
    mysql --user=root --password=babar ansible
    --host=localhost --batch --skip-column-names
    --execute="SELECT LastName from Persons"
  register: stuff
  always_run: True
  changed_when: False

- name: Do something with stuff
  debug: "{{ item }}"
  with_items: stuff.stdout.split

#- name: Configure etc
#  template: src=templates/titi.txt dest=/home/stack/titi.txt backup=yes
#  with_items:
#    - titi.txt
