---
- hosts: localhost
  vars:
  remote_user: root
  vars_files : 
    - vars/mysqkoukoul.yml
 
  tasks:
  - include : tasks/select.yml
  
- hosts: localhost
  vars:
  remote_user: root
  vars_files :
    - vars/mysqkoukoul.yml

  tasks:
  - include : tasks/copy.yml
